// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1WQ7EZ6Kfzs1J0hNFMYHGPPXaOjUWDE',
    appId: '1:906279081203:web:92f39cd1d2ec615655d386',
    messagingSenderId: '906279081203',
    projectId: 'myapps-e2124',
    authDomain: 'myapps-e2124.firebaseapp.com',
    databaseURL: 'https://myapps-e2124-default-rtdb.firebaseio.com',
    storageBucket: 'myapps-e2124.appspot.com',
    measurementId: 'G-2V5EEGWX7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx5SBJbWzMPARwUZoZSqPQkwCUEUT4iKM',
    appId: '1:906279081203:android:9c6942ab2de23d6e55d386',
    messagingSenderId: '906279081203',
    projectId: 'myapps-e2124',
    databaseURL: 'https://myapps-e2124-default-rtdb.firebaseio.com',
    storageBucket: 'myapps-e2124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRHCsauLjJLwxqddViBKLzgvMzFl3W_Q',
    appId: '1:906279081203:ios:b0c7ddf25a68a97f55d386',
    messagingSenderId: '906279081203',
    projectId: 'myapps-e2124',
    databaseURL: 'https://myapps-e2124-default-rtdb.firebaseio.com',
    storageBucket: 'myapps-e2124.appspot.com',
    androidClientId: '906279081203-dvmm2r1niq72es8i6u2eerb00uu7c66b.apps.googleusercontent.com',
    iosClientId: '906279081203-6tp25hgf98fmmoh64od9v13qi0fh3eps.apps.googleusercontent.com',
    iosBundleId: 'com.example.policeFeedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRHCsauLjJLwxqddViBKLzgvMzFl3W_Q',
    appId: '1:906279081203:ios:b0c7ddf25a68a97f55d386',
    messagingSenderId: '906279081203',
    projectId: 'myapps-e2124',
    databaseURL: 'https://myapps-e2124-default-rtdb.firebaseio.com',
    storageBucket: 'myapps-e2124.appspot.com',
    androidClientId: '906279081203-dvmm2r1niq72es8i6u2eerb00uu7c66b.apps.googleusercontent.com',
    iosClientId: '906279081203-6tp25hgf98fmmoh64od9v13qi0fh3eps.apps.googleusercontent.com',
    iosBundleId: 'com.example.policeFeedback',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1WQ7EZ6Kfzs1J0hNFMYHGPPXaOjUWDE',
    appId: '1:906279081203:web:c6693193c2c9b71455d386',
    messagingSenderId: '906279081203',
    projectId: 'myapps-e2124',
    authDomain: 'myapps-e2124.firebaseapp.com',
    databaseURL: 'https://myapps-e2124-default-rtdb.firebaseio.com',
    storageBucket: 'myapps-e2124.appspot.com',
    measurementId: 'G-1RDCJ8L4GP',
  );
}
